////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Utility.cpp
// Robert M. Baker | Created : 22FEB12 | Last Modified : 28JAN16 by Robert M. Baker
// Version : 1.0.0
// This is a source file for 'QMXStdLib'; it defines the implementation for a general utility class.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2011-2016 QuantuMatriX Software, LLP.
//
// This file is part of 'QMXStdLib'.
//
// 'QMXStdLib' is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option) any later version.
//
// 'QMXStdLib' is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
// A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License along with 'QMXStdLib'.  If not, see <http://www.gnu.org/licenses/>.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
  * @file
  * @author  Robert M. Baker
  * @date    Created : 22FEB12
  * @date    Last Modified : 28JAN16 by Robert M. Baker
  * @version 1.0.0
  *
  * @brief This source file defines the implementation for a general utility class.
  *
  * @section Description
  *
  * This source file defines the implementation for a general utility class.
  *
  * @section License
  *
  * Copyright (C) 2011-2016 QuantuMatriX Software, LLP.
  *
  * This file is part of 'QMXStdLib'.
  *
  * 'QMXStdLib' is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free
  * Software Foundation, either version 3 of the License, or (at your option) any later version.
  *
  * 'QMXStdLib' is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
  * A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
  *
  * You should have received a copy of the GNU Lesser General Public License along with 'QMXStdLib'.  If not, see <http://www.gnu.org/licenses/>.
  */

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Header Files
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include <Utility.hpp>

using namespace std;

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Start of the 'QMXStdLib' Namespace
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

namespace QMXStdLib
{

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Static Field Initializers for the 'Utility' Class
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

const StringPair Utility::Languages[ UTILITY_LANGUAGES ] = { make_pair( u8"Abkhaz",              u8"ab" ),
                                                             make_pair( u8"Afar",                u8"aa" ),
                                                             make_pair( u8"Afrikaans",           u8"af" ),
                                                             make_pair( u8"Akan",                u8"ak" ),
                                                             make_pair( u8"Albanian",            u8"sq" ),
                                                             make_pair( u8"Alemannic ",          u8"gsw" ),
                                                             make_pair( u8"Amharic",             u8"am" ),
                                                             make_pair( u8"Arabic",              u8"ar" ),
                                                             make_pair( u8"Aragonese",           u8"an" ),
                                                             make_pair( u8"Armenian",            u8"hy" ),
                                                             make_pair( u8"Assamese",            u8"as" ),
                                                             make_pair( u8"Avaric",              u8"av" ),
                                                             make_pair( u8"Avestan",             u8"ae" ),
                                                             make_pair( u8"Aymara",              u8"ay" ),
                                                             make_pair( u8"Azerbaijani",         u8"az" ),
                                                             make_pair( u8"Bambara",             u8"bm" ),
                                                             make_pair( u8"Banjar",              u8"bj" ),
                                                             make_pair( u8"Bashkir",             u8"ba" ),
                                                             make_pair( u8"Basque",              u8"eu" ),
                                                             make_pair( u8"Belarusian",          u8"be" ),
                                                             make_pair( u8"Bengali",             u8"bn" ),
                                                             make_pair( u8"Bihari",              u8"bh" ),
                                                             make_pair( u8"Bislama",             u8"bi" ),
                                                             make_pair( u8"Bosnian",             u8"bs" ),
                                                             make_pair( u8"Breton",              u8"br" ),
                                                             make_pair( u8"Bulgarian",           u8"bg" ),
                                                             make_pair( u8"Burmese",             u8"my" ),
                                                             make_pair( u8"Catalan",             u8"ca" ),
                                                             make_pair( u8"Chamorro",            u8"ch" ),
                                                             make_pair( u8"Chechen",             u8"ce" ),
                                                             make_pair( u8"Chichewa",            u8"ny" ),
                                                             make_pair( u8"Chinese",             u8"zh" ),
                                                             make_pair( u8"Chuvash",             u8"cv" ),
                                                             make_pair( u8"Cornish",             u8"kw" ),
                                                             make_pair( u8"Corsican",            u8"co" ),
                                                             make_pair( u8"Cree",                u8"cr" ),
                                                             make_pair( u8"Croatian",            u8"hr" ),
                                                             make_pair( u8"Czech",               u8"cs" ),
                                                             make_pair( u8"Danish",              u8"da" ),
                                                             make_pair( u8"Dayak",               u8"da" ),
                                                             make_pair( u8"Divehi",              u8"dv" ),
                                                             make_pair( u8"Dutch",               u8"nl" ),
                                                             make_pair( u8"Dzongkha",            u8"dz" ),
                                                             make_pair( u8"English",             u8"en" ),
                                                             make_pair( u8"Esperanto",           u8"eo" ),
                                                             make_pair( u8"Estonian",            u8"et" ),
                                                             make_pair( u8"Ewe",                 u8"ee" ),
                                                             make_pair( u8"Faroese",             u8"fo" ),
                                                             make_pair( u8"Fijian",              u8"fj" ),
                                                             make_pair( u8"Finnish",             u8"fi" ),
                                                             make_pair( u8"French",              u8"fr" ),
                                                             make_pair( u8"Fula",                u8"ff" ),
                                                             make_pair( u8"Galician",            u8"gl" ),
                                                             make_pair( u8"Ganda",               u8"lg" ),
                                                             make_pair( u8"Georgian",            u8"ka" ),
                                                             make_pair( u8"German",              u8"de" ),
                                                             make_pair( u8"Greek",               u8"el" ),
                                                             make_pair( u8"Guaraní",             u8"gn" ),
                                                             make_pair( u8"Gujarati",            u8"gu" ),
                                                             make_pair( u8"Haitian",             u8"ht" ),
                                                             make_pair( u8"Hausa",               u8"ha" ),
                                                             make_pair( u8"Hebrew",              u8"he" ),
                                                             make_pair( u8"Herero",              u8"hz" ),
                                                             make_pair( u8"Hindi",               u8"hi" ),
                                                             make_pair( u8"Hiri Motu",           u8"ho" ),
                                                             make_pair( u8"Hungarian",           u8"hu" ),
                                                             make_pair( u8"Icelandic",           u8"is" ),
                                                             make_pair( u8"Ido",                 u8"io" ),
                                                             make_pair( u8"Igbo",                u8"ig" ),
                                                             make_pair( u8"Indonesian",          u8"id" ),
                                                             make_pair( u8"Interlingua",         u8"ia" ),
                                                             make_pair( u8"Interlingue",         u8"ie" ),
                                                             make_pair( u8"Inuktitut",           u8"iu" ),
                                                             make_pair( u8"Inupiaq",             u8"ik" ),
                                                             make_pair( u8"Irish",               u8"ga" ),
                                                             make_pair( u8"Italian",             u8"it" ),
                                                             make_pair( u8"Japanese",            u8"ja" ),
                                                             make_pair( u8"Javanese",            u8"jv" ),
                                                             make_pair( u8"Kalaallisut",         u8"kl" ),
                                                             make_pair( u8"Kannada",             u8"kn" ),
                                                             make_pair( u8"Kanuri",              u8"kr" ),
                                                             make_pair( u8"Kashmiri",            u8"ks" ),
                                                             make_pair( u8"Kazakh",              u8"kk" ),
                                                             make_pair( u8"Khmer",               u8"km" ),
                                                             make_pair( u8"Kikuyu",              u8"ki" ),
                                                             make_pair( u8"Kinyarwanda",         u8"rw" ),
                                                             make_pair( u8"Kirundi",             u8"rn" ),
                                                             make_pair( u8"Komi",                u8"kv" ),
                                                             make_pair( u8"Kongo",               u8"kg" ),
                                                             make_pair( u8"Korean",              u8"ko" ),
                                                             make_pair( u8"Kurdish",             u8"ku" ),
                                                             make_pair( u8"Kwanyama",            u8"kj" ),
                                                             make_pair( u8"Kyrgyz",              u8"ky" ),
                                                             make_pair( u8"Lao",                 u8"lo" ),
                                                             make_pair( u8"Latin",               u8"la" ),
                                                             make_pair( u8"Latvian",             u8"lv" ),
                                                             make_pair( u8"Limburgish",          u8"li" ),
                                                             make_pair( u8"Lingala",             u8"ln" ),
                                                             make_pair( u8"Lithuanian",          u8"lt" ),
                                                             make_pair( u8"Luba-Katanga",        u8"lu" ),
                                                             make_pair( u8"Luxembourgish",       u8"lb" ),
                                                             make_pair( u8"Macedonian",          u8"mk" ),
                                                             make_pair( u8"Malagasy",            u8"mg" ),
                                                             make_pair( u8"Malay",               u8"ms" ),
                                                             make_pair( u8"Malayalam",           u8"ml" ),
                                                             make_pair( u8"Maltese",             u8"mt" ),
                                                             make_pair( u8"Manx",                u8"gv" ),
                                                             make_pair( u8"Marathi",             u8"mr" ),
                                                             make_pair( u8"Marshallese",         u8"mh" ),
                                                             make_pair( u8"Mongolian",           u8"mn" ),
                                                             make_pair( u8"Māori",               u8"mi" ),
                                                             make_pair( u8"Nauru",               u8"na" ),
                                                             make_pair( u8"Navajo",              u8"nv" ),
                                                             make_pair( u8"Ndonga",              u8"ng" ),
                                                             make_pair( u8"Nepali",              u8"ne" ),
                                                             make_pair( u8"North Ndebele",       u8"nd" ),
                                                             make_pair( u8"Northern Sami",       u8"se" ),
                                                             make_pair( u8"Norwegian",           u8"no" ),
                                                             make_pair( u8"Norwegian Bokmål",    u8"nb" ),
                                                             make_pair( u8"Norwegian Nynorsk",   u8"nn" ),
                                                             make_pair( u8"Nuosu",               u8"ii" ),
                                                             make_pair( u8"Occitan",             u8"oc" ),
                                                             make_pair( u8"Ojibwe",              u8"oj" ),
                                                             make_pair( u8"Old Church Slavonic", u8"cu" ),
                                                             make_pair( u8"Oriya",               u8"or" ),
                                                             make_pair( u8"Oromo",               u8"om" ),
                                                             make_pair( u8"Ossetian",            u8"os" ),
                                                             make_pair( u8"Panjabi",             u8"pa" ),
                                                             make_pair( u8"Pashto",              u8"ps" ),
                                                             make_pair( u8"Persian",             u8"fa" ),
                                                             make_pair( u8"Polish",              u8"pl" ),
                                                             make_pair( u8"Portuguese",          u8"pt" ),
                                                             make_pair( u8"Pāli",                u8"pi" ),
                                                             make_pair( u8"Quechua",             u8"qu" ),
                                                             make_pair( u8"Romanian",            u8"ro" ),
                                                             make_pair( u8"Romansh",             u8"rm" ),
                                                             make_pair( u8"Russian",             u8"ru" ),
                                                             make_pair( u8"Samoan",              u8"sm" ),
                                                             make_pair( u8"Sango",               u8"sg" ),
                                                             make_pair( u8"Sanskrit",            u8"sa" ),
                                                             make_pair( u8"Sardinian",           u8"sc" ),
                                                             make_pair( u8"Scottish Gaelic",     u8"gd" ),
                                                             make_pair( u8"Serbian",             u8"sr" ),
                                                             make_pair( u8"Shona",               u8"sn" ),
                                                             make_pair( u8"Sindhi",              u8"sd" ),
                                                             make_pair( u8"Sinhala",             u8"si" ),
                                                             make_pair( u8"Slovak",              u8"sk" ),
                                                             make_pair( u8"Slovene",             u8"sl" ),
                                                             make_pair( u8"Somali",              u8"so" ),
                                                             make_pair( u8"South Ndebele",       u8"nr" ),
                                                             make_pair( u8"Southern Sotho",      u8"st" ),
                                                             make_pair( u8"Spanish",             u8"es" ),
                                                             make_pair( u8"Sundanese",           u8"su" ),
                                                             make_pair( u8"Swahili",             u8"sw" ),
                                                             make_pair( u8"Swati",               u8"ss" ),
                                                             make_pair( u8"Swedish",             u8"sv" ),
                                                             make_pair( u8"Tagalog",             u8"tl" ),
                                                             make_pair( u8"Tahitian",            u8"ty" ),
                                                             make_pair( u8"Tajik",               u8"tg" ),
                                                             make_pair( u8"Tamil",               u8"ta" ),
                                                             make_pair( u8"Tatar",               u8"tt" ),
                                                             make_pair( u8"Telugu",              u8"te" ),
                                                             make_pair( u8"Thai",                u8"th" ),
                                                             make_pair( u8"Tibetan",             u8"bo" ),
                                                             make_pair( u8"Tigrinya",            u8"ti" ),
                                                             make_pair( u8"Tonga",               u8"to" ),
                                                             make_pair( u8"Tsonga",              u8"ts" ),
                                                             make_pair( u8"Tswana",              u8"tn" ),
                                                             make_pair( u8"Turkish",             u8"tr" ),
                                                             make_pair( u8"Turkmen",             u8"tk" ),
                                                             make_pair( u8"Twi",                 u8"tw" ),
                                                             make_pair( u8"Uighur",              u8"ug" ),
                                                             make_pair( u8"Ukrainian",           u8"uk" ),
                                                             make_pair( u8"Urdu",                u8"ur" ),
                                                             make_pair( u8"Uzbek",               u8"uz" ),
                                                             make_pair( u8"Venda",               u8"ve" ),
                                                             make_pair( u8"Vietnamese",          u8"vi" ),
                                                             make_pair( u8"Volapük",             u8"vo" ),
                                                             make_pair( u8"Walloon",             u8"wa" ),
                                                             make_pair( u8"Welsh",               u8"cy" ),
                                                             make_pair( u8"Western Frisian",     u8"fy" ),
                                                             make_pair( u8"Wolof",               u8"wo" ),
                                                             make_pair( u8"Xhosa",               u8"xh" ),
                                                             make_pair( u8"Yiddish",             u8"yi" ),
                                                             make_pair( u8"Yoruba",              u8"yo" ),
                                                             make_pair( u8"Zhuang",              u8"za" ),
                                                             make_pair( u8"Zulu",                u8"zu" ) };
const StringPair Utility::Countries[ UTILITY_COUNTRIES ] = { make_pair( u8"Afghanistan",                                  u8"AF" ),
                                                             make_pair( u8"Åland Islands",                                u8"AX" ),
                                                             make_pair( u8"Albania",                                      u8"AL" ),
                                                             make_pair( u8"Algeria",                                      u8"DZ" ),
                                                             make_pair( u8"American Samoa",                               u8"AS" ),
                                                             make_pair( u8"Andorra",                                      u8"AD" ),
                                                             make_pair( u8"Angola",                                       u8"AO" ),
                                                             make_pair( u8"Anguilla",                                     u8"AI" ),
                                                             make_pair( u8"Antarctica",                                   u8"AQ" ),
                                                             make_pair( u8"Antigua and Barbuda",                          u8"AG" ),
                                                             make_pair( u8"Argentina",                                    u8"AR" ),
                                                             make_pair( u8"Armenia",                                      u8"AM" ),
                                                             make_pair( u8"Aruba",                                        u8"AW" ),
                                                             make_pair( u8"Australia",                                    u8"AU" ),
                                                             make_pair( u8"Austria",                                      u8"AT" ),
                                                             make_pair( u8"Azerbaijan",                                   u8"AZ" ),
                                                             make_pair( u8"The Bahamas",                                  u8"BS" ),
                                                             make_pair( u8"Bahrain",                                      u8"BH" ),
                                                             make_pair( u8"Bangladesh",                                   u8"BD" ),
                                                             make_pair( u8"Barbados",                                     u8"BB" ),
                                                             make_pair( u8"Belarus",                                      u8"BY" ),
                                                             make_pair( u8"Belgium",                                      u8"BE" ),
                                                             make_pair( u8"Belize",                                       u8"BZ" ),
                                                             make_pair( u8"Benin",                                        u8"BJ" ),
                                                             make_pair( u8"Bermuda",                                      u8"BM" ),
                                                             make_pair( u8"Bhutan",                                       u8"BT" ),
                                                             make_pair( u8"Bolivia",                                      u8"BO" ),
                                                             make_pair( u8"Caribbean Netherlands",                        u8"BQ" ),
                                                             make_pair( u8"Bosnia and Herzegovina",                       u8"BA" ),
                                                             make_pair( u8"Botswana",                                     u8"BW" ),
                                                             make_pair( u8"Bouvet Island",                                u8"BV" ),
                                                             make_pair( u8"Brazil",                                       u8"BR" ),
                                                             make_pair( u8"British Indian Ocean Territory",               u8"IO" ),
                                                             make_pair( u8"Brunei",                                       u8"BN" ),
                                                             make_pair( u8"Bulgaria",                                     u8"BG" ),
                                                             make_pair( u8"Burkina Faso",                                 u8"BF" ),
                                                             make_pair( u8"Burundi",                                      u8"BI" ),
                                                             make_pair( u8"Cambodia",                                     u8"KH" ),
                                                             make_pair( u8"Cameroon",                                     u8"CM" ),
                                                             make_pair( u8"Canada",                                       u8"CA" ),
                                                             make_pair( u8"Cape Verde",                                   u8"CV" ),
                                                             make_pair( u8"Cayman Islands",                               u8"KY" ),
                                                             make_pair( u8"Central African Republic",                     u8"CF" ),
                                                             make_pair( u8"Chad",                                         u8"TD" ),
                                                             make_pair( u8"Chile",                                        u8"CL" ),
                                                             make_pair( u8"China",                                        u8"CN" ),
                                                             make_pair( u8"Christmas Island",                             u8"CX" ),
                                                             make_pair( u8"Cocos (Keeling) Islands",                      u8"CC" ),
                                                             make_pair( u8"Colombia",                                     u8"CO" ),
                                                             make_pair( u8"Comoros",                                      u8"KM" ),
                                                             make_pair( u8"Congo",                                        u8"CG" ),
                                                             make_pair( u8"Democratic Republic of the Congo",             u8"CD" ),
                                                             make_pair( u8"Cook Islands",                                 u8"CK" ),
                                                             make_pair( u8"Costa Rica",                                   u8"CR" ),
                                                             make_pair( u8"Côte d'Ivoire",                                u8"CI" ),
                                                             make_pair( u8"Croatia",                                      u8"HR" ),
                                                             make_pair( u8"Cuba",                                         u8"CU" ),
                                                             make_pair( u8"Curaçao",                                      u8"CW" ),
                                                             make_pair( u8"Cyprus",                                       u8"CY" ),
                                                             make_pair( u8"Czech Republic",                               u8"CZ" ),
                                                             make_pair( u8"Denmark",                                      u8"DK" ),
                                                             make_pair( u8"Djibouti",                                     u8"DJ" ),
                                                             make_pair( u8"Dominica",                                     u8"DM" ),
                                                             make_pair( u8"Dominican Republic",                           u8"DO" ),
                                                             make_pair( u8"Ecuador",                                      u8"EC" ),
                                                             make_pair( u8"Egypt",                                        u8"EG" ),
                                                             make_pair( u8"El Salvador",                                  u8"SV" ),
                                                             make_pair( u8"Equatorial Guinea",                            u8"GQ" ),
                                                             make_pair( u8"Eritrea",                                      u8"ER" ),
                                                             make_pair( u8"Estonia",                                      u8"EE" ),
                                                             make_pair( u8"Ethiopia",                                     u8"ET" ),
                                                             make_pair( u8"Falkland Islands",                             u8"FK" ),
                                                             make_pair( u8"Faroe Islands",                                u8"FO" ),
                                                             make_pair( u8"Fiji",                                         u8"FJ" ),
                                                             make_pair( u8"Finland",                                      u8"FI" ),
                                                             make_pair( u8"France",                                       u8"FR" ),
                                                             make_pair( u8"French Guiana",                                u8"GF" ),
                                                             make_pair( u8"French Polynesia",                             u8"PF" ),
                                                             make_pair( u8"French Southern and Antarctic Lands",          u8"TF" ),
                                                             make_pair( u8"Gabon",                                        u8"GA" ),
                                                             make_pair( u8"The Gambia",                                   u8"GM" ),
                                                             make_pair( u8"Georgia",                                      u8"GE" ),
                                                             make_pair( u8"Germany",                                      u8"DE" ),
                                                             make_pair( u8"Ghana",                                        u8"GH" ),
                                                             make_pair( u8"Gibraltar",                                    u8"GI" ),
                                                             make_pair( u8"Greece",                                       u8"GR" ),
                                                             make_pair( u8"Greenland",                                    u8"GL" ),
                                                             make_pair( u8"Grenada",                                      u8"GD" ),
                                                             make_pair( u8"Guadeloupe",                                   u8"GP" ),
                                                             make_pair( u8"Guam",                                         u8"GU" ),
                                                             make_pair( u8"Guatemala",                                    u8"GT" ),
                                                             make_pair( u8"Guernsey",                                     u8"GG" ),
                                                             make_pair( u8"Guinea",                                       u8"GN" ),
                                                             make_pair( u8"Guinea-Bissau",                                u8"GW" ),
                                                             make_pair( u8"Guyana",                                       u8"GY" ),
                                                             make_pair( u8"Haiti",                                        u8"HT" ),
                                                             make_pair( u8"Heard Island and McDonald Islands",            u8"HM" ),
                                                             make_pair( u8"Vatican City",                                 u8"VA" ),
                                                             make_pair( u8"Honduras",                                     u8"HN" ),
                                                             make_pair( u8"Hong Kong",                                    u8"HK" ),
                                                             make_pair( u8"Hungary",                                      u8"HU" ),
                                                             make_pair( u8"Iceland",                                      u8"IS" ),
                                                             make_pair( u8"India",                                        u8"IN" ),
                                                             make_pair( u8"Indonesia",                                    u8"ID" ),
                                                             make_pair( u8"Iran",                                         u8"IR" ),
                                                             make_pair( u8"Iraq",                                         u8"IQ" ),
                                                             make_pair( u8"Republic of Ireland",                          u8"IE" ),
                                                             make_pair( u8"Isle of Man",                                  u8"IM" ),
                                                             make_pair( u8"Israel",                                       u8"IL" ),
                                                             make_pair( u8"Italy",                                        u8"IT" ),
                                                             make_pair( u8"Jamaica",                                      u8"JM" ),
                                                             make_pair( u8"Japan",                                        u8"JP" ),
                                                             make_pair( u8"Jersey",                                       u8"JE" ),
                                                             make_pair( u8"Jordan",                                       u8"JO" ),
                                                             make_pair( u8"Kazakhstan",                                   u8"KZ" ),
                                                             make_pair( u8"Kenya",                                        u8"KE" ),
                                                             make_pair( u8"Kiribati",                                     u8"KI" ),
                                                             make_pair( u8"North Korea",                                  u8"KP" ),
                                                             make_pair( u8"South Korea",                                  u8"KR" ),
                                                             make_pair( u8"Kuwait",                                       u8"KW" ),
                                                             make_pair( u8"Kyrgyzstan",                                   u8"KG" ),
                                                             make_pair( u8"Laos",                                         u8"LA" ),
                                                             make_pair( u8"Latvia",                                       u8"LV" ),
                                                             make_pair( u8"Lebanon",                                      u8"LB" ),
                                                             make_pair( u8"Lesotho",                                      u8"LS" ),
                                                             make_pair( u8"Liberia",                                      u8"LR" ),
                                                             make_pair( u8"Libya",                                        u8"LY" ),
                                                             make_pair( u8"Liechtenstein",                                u8"LI" ),
                                                             make_pair( u8"Lithuania",                                    u8"LT" ),
                                                             make_pair( u8"Luxembourg",                                   u8"LU" ),
                                                             make_pair( u8"Macau",                                        u8"MO" ),
                                                             make_pair( u8"Republic of Macedonia",                        u8"MK" ),
                                                             make_pair( u8"Madagascar",                                   u8"MG" ),
                                                             make_pair( u8"Malawi",                                       u8"MW" ),
                                                             make_pair( u8"Malaysia",                                     u8"MY" ),
                                                             make_pair( u8"Maldives",                                     u8"MV" ),
                                                             make_pair( u8"Mali",                                         u8"ML" ),
                                                             make_pair( u8"Malta",                                        u8"MT" ),
                                                             make_pair( u8"Marshall Islands",                             u8"MH" ),
                                                             make_pair( u8"Martinique",                                   u8"MQ" ),
                                                             make_pair( u8"Mauritania",                                   u8"MR" ),
                                                             make_pair( u8"Mauritius",                                    u8"MU" ),
                                                             make_pair( u8"Mayotte",                                      u8"YT" ),
                                                             make_pair( u8"Mexico",                                       u8"MX" ),
                                                             make_pair( u8"Federated States of Micronesia",               u8"FM" ),
                                                             make_pair( u8"Moldova",                                      u8"MD" ),
                                                             make_pair( u8"Monaco",                                       u8"MC" ),
                                                             make_pair( u8"Mongolia",                                     u8"MN" ),
                                                             make_pair( u8"Montenegro",                                   u8"ME" ),
                                                             make_pair( u8"Montserrat",                                   u8"MS" ),
                                                             make_pair( u8"Morocco",                                      u8"MA" ),
                                                             make_pair( u8"Mozambique",                                   u8"MZ" ),
                                                             make_pair( u8"Myanmar",                                      u8"MM" ),
                                                             make_pair( u8"Namibia",                                      u8"NA" ),
                                                             make_pair( u8"Nauru",                                        u8"NR" ),
                                                             make_pair( u8"Nepal",                                        u8"NP" ),
                                                             make_pair( u8"Netherlands",                                  u8"NL" ),
                                                             make_pair( u8"New Caledonia",                                u8"NC" ),
                                                             make_pair( u8"New Zealand",                                  u8"NZ" ),
                                                             make_pair( u8"Nicaragua",                                    u8"NI" ),
                                                             make_pair( u8"Niger",                                        u8"NE" ),
                                                             make_pair( u8"Nigeria",                                      u8"NG" ),
                                                             make_pair( u8"Niue",                                         u8"NU" ),
                                                             make_pair( u8"Norfolk Island",                               u8"NF" ),
                                                             make_pair( u8"Northern Mariana Islands",                     u8"MP" ),
                                                             make_pair( u8"Norway",                                       u8"NO" ),
                                                             make_pair( u8"Oman",                                         u8"OM" ),
                                                             make_pair( u8"Pakistan",                                     u8"PK" ),
                                                             make_pair( u8"Palau",                                        u8"PW" ),
                                                             make_pair( u8"Palestinian Territories",                      u8"PS" ),
                                                             make_pair( u8"Panama",                                       u8"PA" ),
                                                             make_pair( u8"Papua New Guinea",                             u8"PG" ),
                                                             make_pair( u8"Paraguay",                                     u8"PY" ),
                                                             make_pair( u8"Peru",                                         u8"PE" ),
                                                             make_pair( u8"Philippines",                                  u8"PH" ),
                                                             make_pair( u8"Pitcairn Islands",                             u8"PN" ),
                                                             make_pair( u8"Poland",                                       u8"PL" ),
                                                             make_pair( u8"Portugal",                                     u8"PT" ),
                                                             make_pair( u8"Puerto Rico",                                  u8"PR" ),
                                                             make_pair( u8"Qatar",                                        u8"QA" ),
                                                             make_pair( u8"Réunion",                                      u8"RE" ),
                                                             make_pair( u8"Romania",                                      u8"RO" ),
                                                             make_pair( u8"Russia",                                       u8"RU" ),
                                                             make_pair( u8"Rwanda",                                       u8"RW" ),
                                                             make_pair( u8"Saint Barthélemy",                             u8"BL" ),
                                                             make_pair( u8"Saint Helena, Ascension and Tristan da Cunha", u8"SH" ),
                                                             make_pair( u8"Saint Kitts and Nevis",                        u8"KN" ),
                                                             make_pair( u8"Saint Lucia",                                  u8"LC" ),
                                                             make_pair( u8"Collectivity of Saint Martin",                 u8"MF" ),
                                                             make_pair( u8"Saint Pierre and Miquelon",                    u8"PM" ),
                                                             make_pair( u8"Saint Vincent and the Grenadines",             u8"VC" ),
                                                             make_pair( u8"Samoa",                                        u8"WS" ),
                                                             make_pair( u8"San Marino",                                   u8"SM" ),
                                                             make_pair( u8"São Tomé and Príncipe",                        u8"ST" ),
                                                             make_pair( u8"Saudi Arabia",                                 u8"SA" ),
                                                             make_pair( u8"Senegal",                                      u8"SN" ),
                                                             make_pair( u8"Serbia",                                       u8"RS" ),
                                                             make_pair( u8"Seychelles",                                   u8"SC" ),
                                                             make_pair( u8"Sierra Leone",                                 u8"SL" ),
                                                             make_pair( u8"Singapore",                                    u8"SG" ),
                                                             make_pair( u8"Sint Maarten",                                 u8"SX" ),
                                                             make_pair( u8"Slovakia",                                     u8"SK" ),
                                                             make_pair( u8"Slovenia",                                     u8"SI" ),
                                                             make_pair( u8"Solomon Islands",                              u8"SB" ),
                                                             make_pair( u8"Somalia",                                      u8"SO" ),
                                                             make_pair( u8"South Africa",                                 u8"ZA" ),
                                                             make_pair( u8"South Georgia and the South Sandwich Islands", u8"GS" ),
                                                             make_pair( u8"South Sudan",                                  u8"SS" ),
                                                             make_pair( u8"Spain",                                        u8"ES" ),
                                                             make_pair( u8"Sri Lanka",                                    u8"LK" ),
                                                             make_pair( u8"Sudan",                                        u8"SD" ),
                                                             make_pair( u8"Suriname",                                     u8"SR" ),
                                                             make_pair( u8"Svalbard and Jan Mayen",                       u8"SJ" ),
                                                             make_pair( u8"Swaziland",                                    u8"SZ" ),
                                                             make_pair( u8"Sweden",                                       u8"SE" ),
                                                             make_pair( u8"Switzerland",                                  u8"CH" ),
                                                             make_pair( u8"Syria",                                        u8"SY" ),
                                                             make_pair( u8"Taiwan",                                       u8"TW" ),
                                                             make_pair( u8"Tajikistan",                                   u8"TJ" ),
                                                             make_pair( u8"Tanzania",                                     u8"TZ" ),
                                                             make_pair( u8"Thailand",                                     u8"TH" ),
                                                             make_pair( u8"East Timor",                                   u8"TL" ),
                                                             make_pair( u8"Togo",                                         u8"TG" ),
                                                             make_pair( u8"Tokelau",                                      u8"TK" ),
                                                             make_pair( u8"Tonga",                                        u8"TO" ),
                                                             make_pair( u8"Trinidad and Tobago",                          u8"TT" ),
                                                             make_pair( u8"Tunisia",                                      u8"TN" ),
                                                             make_pair( u8"Turkey",                                       u8"TR" ),
                                                             make_pair( u8"Turkmenistan",                                 u8"TM" ),
                                                             make_pair( u8"Turks and Caicos Islands",                     u8"TC" ),
                                                             make_pair( u8"Tuvalu",                                       u8"TV" ),
                                                             make_pair( u8"Uganda",                                       u8"UG" ),
                                                             make_pair( u8"Ukraine",                                      u8"UA" ),
                                                             make_pair( u8"United Arab Emirates",                         u8"AE" ),
                                                             make_pair( u8"United Kingdom",                               u8"GB" ),
                                                             make_pair( u8"United States",                                u8"US" ),
                                                             make_pair( u8"United States Minor Outlying Islands",         u8"UM" ),
                                                             make_pair( u8"Uruguay",                                      u8"UY" ),
                                                             make_pair( u8"Uzbekistan",                                   u8"UZ" ),
                                                             make_pair( u8"Vanuatu",                                      u8"VU" ),
                                                             make_pair( u8"Venezuela",                                    u8"VE" ),
                                                             make_pair( u8"Vietnam",                                      u8"VN" ),
                                                             make_pair( u8"British Virgin Islands",                       u8"VG" ),
                                                             make_pair( u8"United States Virgin Islands",                 u8"VI" ),
                                                             make_pair( u8"Wallis and Futuna",                            u8"WF" ),
                                                             make_pair( u8"Western Sahara",                               u8"EH" ),
                                                             make_pair( u8"Yemen",                                        u8"YE" ),
                                                             make_pair( u8"Zambia",                                       u8"ZM" ),
                                                             make_pair( u8"Zimbabwe",                                     u8"ZW" ) };
mt19937 Utility::Generator;

} // 'QMXStdLib' Namespace

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// End of the 'QMXStdLib' Namespace
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// End of 'Utility.cpp'
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
